### ISSUE TITLE
Incorrect icon for servers without image

### ISSUE THREAD

**Issue by FlixProd** [zaanposni/discord-masz#330]
**See image below:**

![image](https://user-images.githubusercontent.com/68478616/126081989-488add0a-213c-4af6-b95a-4eb0860347a0.png)

**Comment by zaanposni** [comment]
This is because discord does not generate images for guilds without icons. 
Instead they use html/css magic (see image).
![grafik](https://user-images.githubusercontent.com/24491035/126125600-c929afd3-b26a-4204-acd4-af3f4182c953.png)
![grafik](https://user-images.githubusercontent.com/24491035/126125628-621bc149-e3ee-4edd-8adb-dae721061b9d.png)


I will try to include a similiar html tag in MASZ in the next release :)

**Comment by zaanposni** [comment]
Hey @FlixProd 

This will be fixed via Pull Request #336 
I even added support for animated guild icons 👀 

Issue will be closed upon merging of the PR. Thanks for your report 🚀
