### ISSUE TITLE
Incorrect link in automod tab

### ISSUE THREAD

**Issue by FlixProd** [zaanposni/discord-masz#439]
When clicking the `View Case` button on an automoderation, the button link is incorrect, resulting in a blank case page.
The button links to `https://masz.url.de/guilds/1234456789/cases/66`, but when the case is opened from the normal ,,Cases" tab, the case opens under the url `https://masz.url.de/guilds/123456789/cases/10` (this is the correct link)

![Gif](https://user-images.githubusercontent.com/68478616/139592102-46ebbe14-231b-4646-8880-d9c0809e0c38.gif)

**Comment by FlixProd** [comment]
Sorry, looks like a local problem only 🙈 On the demo instance it works correctly

**Comment by zaanposni** [comment]
This is in fact a real problem.
Let me explain it really quick. There are two different ids.
On database internal `id` (auto_increment) and one `caseId` that is only auto_increment for each guild.
The `caseId` should be used for everything since it is unique per guild and is also what the user is supposed to see.
On the demo instance there are only 50 cases per default and only one guild which means that the `id` always equals the `caseId`.
In your case you might have multiple guilds or cases that got deleted already which means the `id` and `caseId` are no longer equal.

Problem is that in [this line](https://github.com/zaanposni/discord-masz/blob/master/backend/masz/Repositories/AutoModerationEventRepository.cs#L79) the `AssociatedCaseId` which is used to generate the link is assigned incorrectly.

I have already adjusted it for release `2.2.0`.
