### ISSUE TITLE
Slash Commands: Extension for a "cleanup all" command

### ISSUE THREAD

**Issue by Bricksmaster** [zaanposni/discord-masz#487]
Currently, the /cleanup slash command is quite limited e.g. to one channel for a specific user. Especially after a server raid, deleting all the messages can cost a lot of time even with the MASZ bot.

Therefore, the slash command should be extended with a "cleanup all" command. Executing this command will delete every message/image/file/etc. from the provided UserID at the whole server. With this command, it is possible to delete problematic messages from a troll/raid user convenient and with less time.

**Comment by zaanposni** [comment]
Deleting all messages might be very slow, I would make two modes for this:
- Only 2 weeks old (this is relative fast)
- Everything (messages older than two weeks need to be deleted one by one with a cooldown of a few seconds)

However, the second mode could possibly make the MASZ instance unstable because discords ratelimit will be triggered very often while using this mode.

Possible solution:
Only use the 2 weeks old mode? How do you feel about that @Bricksmaster ?

**Comment by Bricksmaster** [comment]
The /cleanup command for all message usually gets used for accounts which were used for spamming. Therefore, there are a lot of new messages but in several channels.
The 2 weeks feature should work well and be default. But there should be an optional feature to delete absolute everything from a user with the warning that it can slow down MASZ.
